### ISSUE TITLE
bandwidth leak

### ISSUE THREAD

**Issue by AnguelSC** [fbricker/muses#14]
The player is consuming my bandwidth web hosting, the same amount consumed by streaming, many GB

**Comment by fbricker** [comment]
Hi, if you use a proxy to stream from your web-server to the player, you will indeed consume the same bandwidth in your web and in your streaming server.

Please check if you're using a proxy. If you do, you should consider getting rid of it.

If you need assistance, please write us using the feedback & support option at muses.org

Thanks!
