### ISSUE TITLE
How to use HTML5 version in an offline application

### ISSUE THREAD

**Issue by jh3141** [fbricker/muses#23]
I'm trying to develop an application for embedding in Electron (which is essentially a Chrome shell bundled with a javascript application for offline use), but I can't see how to download the HTML5 version so I can use it in this context (Flash isn't supported).  Can you provide instructions for this?

**Comment by fbricker** [comment]
Hi, right now the HTML5 version is not available for download since we're still making changes before releasing a downloadable version. You can use it hosted from hosted.muses.org or wait until a release is open for dowload.
