### ISSUE TITLE
Opus

### ISSUE THREAD

**Issue by Allmoz** [fbricker/muses#4]
i was reading about opus codec, and find it interesting

also found a a haxe extension: 
https://github.com/soywiz/haxe-nme-opus/blob/master/haxelib.xml

the bad thing is that is not updated, opus is already in 1.0.2 and 1.1 alpha

and wiki say : "Opus support is mandatory for WebRTC implementations"

so firefox and chrome  are already suporting it

is something to keep in mind for the future

**Comment by fbricker** [comment]
Hi, I'm closing this issue since Opus is now supported on HTML5 version (at least on browsers that supports opus).
